name: WebdriverIO

on:
  push:
    branches: [ master, release]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Install Chromium Browser
        run: sudo apt-get install chromium-browser
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Run WebdriverIO Tests
        run: npm test
      - name: Generate Allure report
        run: allure generate

